### ISSUE TITLE
Forbidden: /fp/process/ - "POST /fp/process/ HTTP/1.1" 403 59

### ISSUE THREAD

**Issue by narzuta** [ImperialCollegeLondon/django-drf-filepond#43]
Hi.
I have a problem with uploading files. I use docker.
I keep getting a bug:

```
Forbidden: /fp/process/
 "POST /fp/process/ HTTP/1.1" 403 59
```

My filepond js config

```
<script>
$(function () {
    $('.course_create_pond').filepond();
    $('.course_create_pond').filepond('allowMultiple', false);
    $('.course_create_pond').filepond.setOptions({
        chunkUploads: true,
        chunkSize: 50000,
        server: {
            url: 'http://localhost:8000/fp',
            process: '/process/',
            patch: '/patch/',
            revert: '/revert/',
            fetch: '/fetch/?target=',
        }
    });
});
</script>
```
urls.py

`path('fp/', include('django_drf_filepond.urls')),`

settings.py

```
if DEBUG:
    DJANGO_DRF_FILEPOND_UPLOAD_TMP = os.path.join(BASE_DIR, 'filepond-temp-uploads')
    DJANGO_DRF_FILEPOND_FILE_STORE_PATH = os.path.join(BASE_DIR, 'stored_uploads')
else:
    DJANGO_DRF_FILEPOND_STORAGES_BACKEND = 'storages.backends.s3boto3.S3Boto3Storage'

```

**Comment by jcohen02** [comment]
Hi @narzuta,
Thanks for reporting this issue and providing the details of your configuration.
Have you been using the example provided in the [tutorial](https://django-drf-filepond.readthedocs.io/en/latest/index.html#document-tutorial/tutorial) in the documentation? (your initial configuration looks similar to that)

I've just set up a test application from scratch based on the instructions in the tutorial but I've used your configuration from above for `settings.py` and `urls.py` and I've also pasted the js configuration you provided above into the [`filepond-jquery-example.html`](https://github.com/ImperialCollegeLondon/django-drf-filepond/blob/master/docs/tutorial/filepond-jquery-example.html) file provided with the tutorial (I changed the class of the `input` element to match your example).

Using this configuration, things seem to work fine and I'm able to successfully upload a file which then ends up in `os.path.join(BASE_DIR, 'filepond-temp-uploads')`.

It would be useful to get a bit more information about your configuration and the circumstances under which this issue is occurring. Can you please confirm:

 - What versions of `Python`, `Django` and `django-drf-filepond` you're running? For my test I'm using Python 3.8, I installed the dependencies using `pip` as described in the tutorial and have ended up with Django==3.0.9 and django-drf-filepond==0.3.0.
 - What server you're using (are you testing using the django dev server - `python manage.py runserver`)?
 - Do you have some sort of authentication configured in the application that you're testing with? I'm assuming not since you're running via `HTTP` rather than `HTTPS` but I'm surprised that you're getting a 403 error.
 - Do you have some sort of reverse proxy in front of the Django server (e.g. nginx)?
 - I presume this problem is occuring when undertaking the initial storage of a temporary upload - that is, you've not got the point of trying to store the upload (either in `DEBUG` mode to `stored_uploads` or in production mode to S3)?

Thanks

**Comment by narzuta** [comment]
Hi, thank you for your reply.
yes i used the tutorial and did everything according to it.
1. I use django 3.0.9 and python 3.8.4, django-drf-filepond 0.3.0
2. Yes in development use python manage.py runserver
```
version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgresql
      - redis
    restart: always
    networks:
      - mentoro-network
  postgresql:
    image: postgres:12.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
    networks:
      - mentoro-network
  redis:
    image: redis:6-buster
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data/
    expose:
      - "6379"
    env_file:
      - ./.env.dev
    networks:
      - mentoro-network

volumes:
  postgres_data:
  redis_data:
networks:
  mentoro-network:
```

3. In development i use http
4. In development version i not use ngnix
5. yes, the same error occurs with S3 and stored_uploads in local
6. that's how i work on this port. above I gave config

additionally I use crispy forms
```
from django import forms
from .models import Course
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div, Column, Field

class CourseForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'title',
            'category',
            'language',
            'price',
            'short_description',
            'description',
            Div('image_preview', css_class=""),
            Div('video_preview', css_class="course_create_pond"),
            Submit('submit', 'Dodaj kurs', css_class='btn btn-success btn-block shadow rounded-0 font-weight-bold')
        )

    class Meta:
        model = Course
        fields = ('title', 'price', 'category', 'language', 'short_description', 'description', 'image_preview', 'video_preview',)
```

and my models.py

```
from django.db import models
from django.utils import timezone
from optimized_image.fields import OptimizedImageField
from simple_history.models import HistoricalRecords
from ckeditor.fields import RichTextField

class CourseCategory(models.Model):
    title = models.CharField(max_length=150, blank=False, null=False)
    history = HistoricalRecords()

    def __str__(self):
        return self.title

class CourseLanguage(models.Model):
    title = models.CharField(max_length=150, blank=False, null=False)
    history = HistoricalRecords()

    def __str__(self):
        return self.title

class Course(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=False, null=False, verbose_name='Tytuł', help_text='Wpisz tytuł Twojego wideo kursu')
    category = models.ForeignKey(CourseCategory, on_delete=models.CASCADE, verbose_name='Kategoria', help_text='Wybierz kategorię w której chcesz dodać kurs')
    language = models.ForeignKey(CourseLanguage, on_delete=models.CASCADE, verbose_name='Język', help_text='Wybierz język w którym są Twoje treści')
    price = models.DecimalField(null=False, blank=False, max_digits=7, decimal_places=2, default='49.99', verbose_name='Cena', help_text='Podaj cenę w złotówkach za która chcesz sprzedawać materiał')
    short_description = RichTextField(blank=False, null=False, verbose_name='Krótki opis', help_text='Dodaj krótki opis. Maksymalna ilość znaków to 500')
    description = RichTextField(blank=False, null=False, verbose_name='Szczegółowy opis', help_text='Podaj szczegółowy opis Twojego materiału.')
    image_preview = OptimizedImageField(upload_to='courses/image_course_preview/%Y/%m/%d/', blank=False, null=False, verbose_name='Zdjęcie podglądowe', help_text='Dodaj zdjęcie podglądowe kursu')
    video_preview = models.FileField(upload_to='courses/image_course_preview/%Y/%m/%d/', blank=False, null=False, verbose_name='Wideo prezentacja', help_text='Dodaj film wideo reklamujący i prezentująćy Twoj wideo kurs')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    history = HistoricalRecords()

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
```

**Comment by jcohen02** [comment]
Hi @narzuta, many thanks for providing this information about your configuration. I've had a go at investigating this. I can't really see what is causing the issue but I think it may be something to do with your docker compose networking configuration. I'm not sure that this issue is the result of a problem with django-drf-filepond.

If I create a cut-down, single container docker-compose configuration based on the example you've given:

```
version: '3.7'

services:
  web:
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ${PWD}/app/:/usr/src/app/
    ports:
      - 8000:8000
    restart: always
    networks:
      - mentoro-network

networks:
  mentoro-network:
```

where the `Dockerfile` in the `app`directory is just a simple Ubuntu 20.04 image with the Python packages installed globally (no virtualenv):

```
FROM ubuntu:20.04

RUN apt-get -y update && apt-get -y install python3 python3-dev python3-venv python3-pip
RUN useradd -ms /bin/bash app

WORKDIR /usr/src/app
RUN pip3 install Django django-drf-filepond
```

When I run this with `docker-compose up` (after manually running the build with `docker-compose build`) the container starts OK and I can access the tutorial web app at `http://localhost:8000/demo/filepond-jquery-example.html` and succesfully upload a file. In the `app` directory, I just have the results of running through the tutorial, so a very basic Django application configured to use `django-drf-filepond` with the [django-drf-filepond demo page](https://raw.githubusercontent.com/ImperialCollegeLondon/django-drf-filepond/master/docs/tutorial/filepond-jquery-example.html).

If I switch the configuration to include the postgres and redis blocks in your docker-compose example, I immediately see issues with loading the demo web page - for some reason, none of the CSS is loaded so there is clearly a difference resulting from the networking configuration. I see that you have an `env` file set up for your containers - I don't know what's in that file but presumably that is setting up some environment variables that could be affecting things?

What Linux distribution are you using? Are you doing anything more advanced in your Dockerfile in the `app` directory than the simple example I've provided above? If so, is there any configuration there that could be causing an issue?

If you are still experiencing issues, could you try and set up a simple test using a basic configuration similar to that shown above and see if this works successfully?
